spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://192.168.56.100:3306/security?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver